const SliderData = [
  {
    org_name: 'Hoppscoth',
    title: 'Self Driving Car',
    Ideas: [
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae dicta magni dolorum ipsam itaque in, voluptatum voluptas ipsa similique at ex quae tempore modi architecto esse cumque vero, soluta ea voluptatem velit illum sapiente sint pariatur. Consectetur nemo possimus sint mollitia libero, adipisci nam in modi eligendi veniam magnam iste aut? Ex cum, in provident commodi, molestias iure quo explicabo nihil animi dolor natus itaque totam illo eaque omnis. Ad vitae hic ea rem fugit vero dignissimos tempore beatae fuga quaerat, laborum ab sequi accusantium suscipit sint quam provident dolorem asperiores commodi at pariatur soluta modi! Quaerat modi laudantium commodi.',
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae dicta magni dolorum ipsam itaque in, voluptatum voluptas ipsa similique at ex quae tempore modi architecto esse cumque vero, soluta ea voluptatem velit illum sapiente sint pariatur. Consectetur nemo possimus sint mollitia libero, adipisci nam in modi eligendi veniam magnam iste aut? Ex cum, in provident commodi, molestias iure quo explicabo nihil animi dolor natus itaque totam illo eaque omnis. Ad vitae hic ea rem fugit vero dignissimos tempore beatae fuga quaerat, laborum ab sequi accusantium suscipit sint quam provident dolorem asperiores commodi at pariatur soluta modi! Quaerat modi laudantium commodi.',
      '2',
      '3',
    ],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all web',
  },
  {
    org_name: 'ABC',
    title: 'Project-2',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all web',
  },
  {
    org_name: 'ABC',
    title: 'Project-3',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all app',
  },
  {
    org_name: 'ABC',
    title: 'Project-4',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all app',
  },
  {
    org_name: 'ABC',
    title: 'Project-5',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all ml',
  },
  {
    org_name: 'ABC',
    title: 'Project-6',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all ml',
  },
  {
    org_name: 'ABC',
    title: 'Project-7',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    tags: 'all web',
  },
];
export default SliderData;
