import imgs from '../../../assets/organizations/asyncAPI4.png'
const SliderData = [
  {
    org_name: 'Hoppscoth',
    title: 'Self Driving Car',
    Ideas: [
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae dicta magni dolorum ipsam itaque in, voluptatum voluptas ipsa similique at ex  ea rem fugit vero asperiores commodi at pariatur soluta modi! Quaerat modi laudantium commodi.',
      'Lorem ipsum dolor sit amet,m commodi.',
      '2',
      '3',
    ],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all web',
  },
  {
    org_name: 'ABC',
    title: 'Project-2',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all web',
  },
  {
    org_name: 'ABC',
    title: 'Project-3',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all app',
  },
  {
    org_name: 'ABC',
    title: 'Project-4',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all app',
  },
  {
    org_name: 'ABC',
    title: 'Project-5',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all ml',
  },
  {
    org_name: 'ABC',
    title: 'Project-6',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all ml',
  },
  {
    org_name: 'ABC',
    title: 'Project-7',
    Ideas: ['1', '2', '3'],
    mentors: ['laxman', 'jhonny'],
    repo_link: 'afjkdfkla',
    org_img:imgs,
    tags: 'all web',
  },
];
export default SliderData;
