const timeLine = [
  {
    date: "1st Oct - 7th Nov",
    topHeading: "1ST OCT - 7TH NOV",
    subHeading: "Student Applications Open",
    content: "",
    contentStyle: { background: "rgb(150, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: true,
  },
  {
    date: "8th Nov",
    topHeading: "8TH NOV",
    subHeading: "Proposal Writing session + Inauguration Ceremony",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "9th Nov - 15th Nov",
    topHeading: "9TH NOV - 15TH NOV",
    subHeading: "Student Proposals submission",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "16th Nov - 25th Nov",
    topHeading: "16TH NOV - 25TH NOV",
    subHeading: "Organisations select proposals",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "25th Nov - 30th Nov",
    topHeading: "25TH NOV - 30TH NOV",
    subHeading: "Community Bonding Phase",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "30th Nov - 30th Jan",
    topHeading: "30TH NOV - 30TH JAN",
    subHeading: "Coding phase",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "30th Jan - 15th Jan",
    topHeading: "30TH JAN - 15TH JAN",
    subHeading: "Mentor Feedback Review",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
];

export default timeLine;
