const timeLine = [
  {
    date: "1st Oct - 23rd Oct",
    topHeading: "1ST OCT-23RD OCT",
    subHeading: "Student Applications Open",
    content: "",
    contentStyle: { background: "rgb(150, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: true,
  },
  {
    date: "24th Oct",
    topHeading: "24TH OCT",
    subHeading: "Proposal Writing session + Inauguration Ceremony",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "25th Oct - 31th Oct",
    topHeading: "25TH OCT-31ST OCT",
    subHeading: "Student Proposals submission",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "1st Nov - 10th Nov",
    topHeading: "1ST NOV-10TH NOV",
    subHeading: "Organisations select proposals",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "10th Nov - 15th Nov",
    topHeading: "10TH NOV - 15TH NOV",
    subHeading: "Community Bonding Phase",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "15th Nov - 15th Jan",
    topHeading: "15TH NOV - 15TH JAN",
    subHeading: "Coding phase",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "15th Jan - 31st Jan",
    topHeading: "15TH JAN - 31ST JAN",
    subHeading: "Mentor Feedback Review",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    active: false,
  },
];

export default timeLine;
