const timeLine = [
  {
    date: "1st Oct - 7th Nov",
    topHeading: "1ST OCT - 7TH NOV",
    subHeading: "Student Applications Open",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "7th Nov",
    topHeading: "7TH NOV",
    subHeading: "Proposal Writing session + Inauguration Ceremony",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "8th Nov - 30th Nov",
    topHeading: "8TH NOV - 30TH NOV",
    subHeading: "Student Proposals submission",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "1st Dec - 5th Dec",
    topHeading: "1ST Dec - 5TH Dec",
    subHeading: "Community Bonding Phase",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: true,
  },
  {
    date: "5th Dec - 5th Feb",
    topHeading: "5TH Dec - 5TH FEB",
    subHeading: "Coding phase",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: false,
  },
  {
    date: "5th Feb - 15th Feb",
    topHeading: "5TH FEB - 15TH FEB",
    subHeading: "Mentor Feedback Review",
    content: "",
    contentStyle: { background: "rgb(33, 150, 243)", color: "white" },
    activeStyle: { background: "rgb(150, 150, 243)", color: "white" },
    active: false,
  },
];

export default timeLine;
